Models/PupilLogin.cs
using System.ComponentModel.DataAnnotations;

namespace IPMO.Models
{
    public class PupilLogin
    {
        [Required(ErrorMessage = "Please enter your email")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter your password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

Controllers/Pupil_LoginController.cs
using IPMO.IServices;
using IPMO.Models;
using IPMO.Models.EmailService;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace IPMO.Controllers
{
    [Route("api/{controller}")]
    public class Pupil_LoginController : Controller
    {
        private readonly IPupilLogin _loginservice;
        private readonly IAuth _auth;
        private readonly IEmailService _emailservice;
        public Pupil_LoginController(IPupilLogin loginservice,
             IAuth auth,
             IEmailService emailservice
            )
        {
            _loginservice = loginservice;           
            _auth = auth;
            _emailservice = emailservice;  
        }
        [HttpGet]
        [Route("login")]
        public IActionResult login()
        {
            return View();
        }
        [HttpPost]
        [Route("login")]
        public async  Task<IActionResult> login(PupilLogin pupil)
        {
            if (ModelState.IsValid)
            {
                bool isPupilExit = _loginservice.PupilValidation(pupil);
                if (isPupilExit == true)
                {
                    
                    //generate token and store into database as well
                    var token = _auth.GenerateTwoFactorTokenAsync(pupil.Email);                
                    var message = new Message(new string[] { pupil.Email! }, "OTP Confirmation", token);
                 //if token has been sent to your email 
                    bool Issent= _emailservice.SendEmail(message);
                    if (Issent == true)
                    {
                        return RedirectToAction("EnterToken");
                    }
                    
                }
                else
                {
                    ModelState.AddModelError("", "Invalid email or password");
                }
            }

            return View();
        }
        [HttpGet]
        public IActionResult EnterToken()
        {
            return View();
        }

        // Recive token from the user and confirm from the database we have already stored
        [HttpPost]
        public IActionResult EnterToken(string token)
            {
            if (ModelState.IsValid)
            {
               bool IsUserExit= _auth.EmailConfirmIfExit(token);
                if (IsUserExit == true)
                {
                    return Ok("user  confirmed successfully");
                }
                else
                {
                    return BadRequest("User not confirmed");
                }
                
            }

            return View();          
              }

    }
}

Views/Pupil_Login/EnterToken.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



<form asp-action="EnterToken" method="post">
    <label>Please Enter Confirmation code we have sent to your Email</label>
    <input type="text" name="token" />
    <button type="submit"> Submit</button>
</form>

Views/Pupil_Login/login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



@model IPMO.Models.PupilLogin;

@{
    ViewBag.Title = "Index";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ENROLLMENT</title>
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css" />
    <script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="../../Content/StyleSheet.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript">

        $(document).ready(function () {
            $.ajax({

                type: 'POST',
                URL: '/UserLogin/Login',
                data: data,
                dataType: 'JSON',
                success: function (data) {
                    datadata = data.status
                    if (status == "1") {
                        window.location.href = '@Url.Action("Index","UserLogin")';
                    }
                }
            });
        });
    </script>
</head>

<body>
    <!------ Include the above in your HEAD tag ---------->
    @using (Html.BeginForm("login", "Pupil_Login", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="container register">
            <div class="row">
                @* <div class="col-md-3 register-left">
            <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt="" />
            <h3>Welcome</h3>
            <p>This Example is for learning MVC Basic Login and Registration Using ADO.NET.</p>
            </div>*@
                <div class="col-md-9 register-right">
                    @*<ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">

                <li class="nav-item">
                <a class="nav-link" id="profile-tab" data-toggle="tab" href="../UserLogin/Login" role="tab" aria-controls="profile" aria-selected="false">Login</a>
                </li>
                </ul>*@
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            <h3 class="register-heading">Login as a User</h3>
                            <div class="row register-form">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.Email, new { @class = "form-control", placeholder = "Enter Email *" })
                                        @Html.ValidationMessageFor(e => e.Email ,"",new {@class="text-danger"})
                                    </div>
                                    <br>

                                    <div class="form-group">
                                        @Html.PasswordFor(e => e.Password, new { id = "password", @class = "form-control", placeholder = "Password *" })
                                        <span id="result"></span>
                                        @Html.ValidationMessageFor(e => e.Password,"",new {@class="text-danger"})
                                    </div>
                                    <br>
                                    <div class="col-md-6">
                                        <input type="submit" class="btnLogin" value="Login" />
                                    </div>      
                                    <br>
                                    <br>
                                    <a asp-action="forgotpassword" asp-controller="ForgtPassword">Forgot password</a>
                                    @if(!ViewData.ModelState.IsValid)
                                    {
                                        <div class="alert alert-danger">
                                            <strong>Error:</strong> @Html.ValidationSummary()
                                        </div>
                                    }
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <script type="text/javascript">
                $(function () {
                    var msg = '@ViewData["result"]';
                    if (msg == '1') {
                        alert("User Details Inserted Successfully");
                        window.location.href = "@Url.Action("Index", "UserLogin")";
                    }
                });
            </script>

        </div>
    }
</body>
</html>